#!/usr/bin/env bash
# tests/test-piper-roundtrip.sh — live integration test: piper TTS → whisper ASR.
#
# Synthesizes text with piper, transcribes with whisper, checks the output
# contains the expected words. Requires models on disk or --auto-download.
#
# Usage:
#   bash tests/test-piper-roundtrip.sh <stelnet_binary> [piper_model]
#
# Exit codes:
#   0 = all tests pass
#   1 = test failure
#   2 = missing dependencies (models, binaries)

set -euo pipefail

STELNET="${1:-build/bin/stelnet}"
PIPER_MODEL="${2:-auto}"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Ensure CMUdict is available for quality phonemization.
# Check common locations; download if missing.
CMUDICT=""
for p in "${STELNET_CMUDICT_PATH:-}" \
         "$HOME/.cache/stelnet/cmudict.dict" \
         "/tmp/cmudict.dict" \
         "models/cmudict.dict"; do
    if [ -f "$p" ] 2>/dev/null; then
        CMUDICT="$p"
        break
    fi
done
if [ -z "$CMUDICT" ]; then
    echo "Downloading CMUdict..."
    mkdir -p "$HOME/.cache/stelnet"
    curl -sL "https://raw.githubusercontent.com/cmusphinx/cmudict/refs/heads/master/cmudict.dict" \
        -o "$HOME/.cache/stelnet/cmudict.dict" 2>/dev/null && \
        CMUDICT="$HOME/.cache/stelnet/cmudict.dict"
fi
if [ -n "$CMUDICT" ]; then
    export STELNET_CMUDICT_PATH="$CMUDICT"
    echo "CMUdict: $CMUDICT"
else
    echo "WARNING: CMUdict not available — quality may be degraded"
fi

PASS=0
FAIL=0

check() {
    local desc="$1" wav="$2" expected="$3"
    # Transcribe
    local transcript
    transcript=$("$STELNET" -m auto --auto-download -l en -f "$wav" -np 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -d '.,!?')
    expected_lower=$(echo "$expected" | tr '[:upper:]' '[:lower:]' | tr -d '.,!?')

    # Check each expected word appears in transcript (substring match —
    # whisper may join words like "sea shore" → "seashore")
    local ok=true
    for word in $expected_lower; do
        if ! echo "$transcript" | grep -qi "$word"; then
            ok=false
            break
        fi
    done

    if $ok; then
        echo "  PASS: $desc"
        echo "        got: $transcript"
        PASS=$((PASS + 1))
    else
        # Retry once — whisper can hallucinate on short utterances
        transcript=$("$STELNET" -m auto --auto-download -l en -f "$wav" -np 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -d '.,!?')
        ok=true
        for word in $expected_lower; do
            if ! echo "$transcript" | grep -qi "$word"; then ok=false; break; fi
        done
        if $ok; then
            echo "  PASS: $desc (retry)"
            echo "        got: $transcript"
            PASS=$((PASS + 1))
        else
            echo "  FAIL: $desc"
            echo "        expected words: $expected_lower"
            echo "        got: $transcript"
            FAIL=$((FAIL + 1))
        fi
    fi
}

# Verify binary exists
if [ ! -x "$STELNET" ]; then
    echo "ERROR: $STELNET not found or not executable" >&2
    exit 2
fi

echo "=== Piper TTS → ASR roundtrip tests ==="
echo "Binary: $STELNET"
echo "Piper model: $PIPER_MODEL"
echo ""

# Determine piper model args
if [ "$PIPER_MODEL" = "auto" ]; then
    PIPER_ARGS="-m auto --auto-download"
else
    PIPER_ARGS="-m $PIPER_MODEL"
fi

# --- Test 1: Plain text with espeak-ng phonemization ---
echo "[1/4] Plain English text (requires espeak-ng)"
"$STELNET" --backend piper $PIPER_ARGS \
    --tts "Hello world" \
    --tts-output "$TMPDIR/t1.wav" 2>/dev/null || {
    echo "  SKIP: espeak-ng not available or synthesis failed"
    FAIL=$((FAIL + 0))  # don't count as failure if espeak missing
    echo ""
    goto_t2=true
}
if [ "${goto_t2:-false}" != "true" ]; then
    check "hello world" "$TMPDIR/t1.wav" "hello world"
fi
echo ""

# --- Test 2: The sentence from the original bug report ---
echo "[2/4] Original bug report sentence"
"$STELNET" --backend piper $PIPER_ARGS \
    --tts "This audio was generated by artificial intelligence." \
    --tts-output "$TMPDIR/t2.wav" 2>/dev/null
check "AI disclosure sentence" "$TMPDIR/t2.wav" "generated artificial intelligence"
echo ""

# --- Test 3: Quick brown fox (all consonants/vowels) ---
echo "[3/4] Quick brown fox (phonetic coverage)"
"$STELNET" --backend piper $PIPER_ARGS \
    --tts "The quick brown fox jumps over the lazy dog." \
    --tts-output "$TMPDIR/t3.wav" 2>/dev/null
check "quick brown fox" "$TMPDIR/t3.wav" "quick brown fox jumps over lazy dog"
echo ""

# --- Test 4: Longer sentence with numbers ---
echo "[4/4] Sentence with diverse phonetics"
"$STELNET" --backend piper $PIPER_ARGS \
    --tts "She sells sea shells by the sea shore." \
    --tts-output "$TMPDIR/t4.wav" 2>/dev/null
check "sea shells" "$TMPDIR/t4.wav" "she sells shore"
echo ""

# --- Summary ---
TOTAL=$((PASS + FAIL))
echo "=== Results: $PASS/$TOTAL passed ==="
if [ "$FAIL" -gt 0 ]; then
    echo "FAILED"
    exit 1
else
    echo "ALL PASSED"
    exit 0
fi
